branch-defaults:
  master:
    environment: DatingApiPrd-env
deploy:
  working_directory: ~/app
  docker:
    - image: circleci/ruby:2.4.3
  #artifact: artifact.zip
environment-defaults:
  DatingApiPrd-env:
    branch: null
    repository: null
global:
  application_name: dating-api-prd
  default_ec2_keyname: AmazonCloud
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Java 8 running on
    64bit Amazon Linux/2.5.4
  default_region: us-east-1
  sc: git
  workspace_type: Application

